name: PR Comment Sample
# on:
#   pull_request:
#     types: [opened]
on: pull_request
jobs:
  pr_comment_sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/github-script@v5
        env:
          BRANCH_NAME: ${{github.head_ref}}
        with:
          github-token: ${{secrets.GITHUB_TOKEN}}
          script: |
            const { BRANCH_NAME } = process.env
            if (!BERANCH_NAME.match(/(HOGEHUGAPIYO-\d+)$/)) { return }
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `[${BRANCH_NAME}](http://example.com/${BRANCH_NAME})`
            })
