name: PR Comment Sample
on: pull_request
# on:
#   pull_request:
#     types: [opened]
jobs:
  pr_comment_sample:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v1
        with:
          message: '[link sample](http://example.com)'
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
